name: "Terraform action"

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE: ${{ secrets.AWS_ROLE }}

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
      pull-requests: write    # This is required for infracost to write on pull requests.

jobs:
  deploytoaws:
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1.7.2
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Seup Tf-init
        run: |
          terraform init
